### PR TITLE
sort strategies by index

### LINKED ISSUE #124: strategies list in vault page is not sorted by index
https://yearn.watch/vault/0xa258C4606Ca8206D8aA700cE2143D7db854D168c

0-n in the queue first, and out of the queue (-1) at the end of the list.

### PR DESCRIPTION
**Pull request by uwe**
PR for #124 

With this PR, the order would be -1, 0, 1, 2, etc.
Should -1 be last?

### CODE REVIEW

**Comment by storming0x** [comment]
> PR for #124
> 
> With this PR, the order would be -1, 0, 1, 2, etc.
> Should -1 be last?

0-n in the queue first, and out of the queue (-1) at the end of the list. @uwe

**Comment by uwe** [comment]
And should there be any secondary sort order (e. g. by report date, name or assets)?

**Comment by storming0x** [comment]
> And should there be any secondary sort order (e. g. by report date, name or assets)?

not for now, just the index is fine to close the issue

**Comment by storming0x** [comment]
https://yearn-hub-git-fork-uwe-sort-strategies-y-finance.vercel.app/vault/0x671a912C10bba0CFA74Cfc2d6Fba9BA1ed9530B2

@uwe seems this one has the -1 at the beginning still, seeing other vaults have the fix correctly
https://yearn-hub-git-fork-uwe-sort-strategies-y-finance.vercel.app/vault/0x5120FeaBd5C21883a4696dBCC5D123d6270637E9

if compared to live site

**Comment by uwe** [comment]
There was one place left, where I forgot to use the sorted array.

**Comment by storming0x** [comment]
LGTM!

**Pull request merged**
