### PR TITLE
refactor: `getWarnings` into util function

### PR DESCRIPTION
**Pull request by karelianpie**
Spotted a TODO in [SingleStrategy/index.tsx#L78](https://github.com/yearn/yearn-watch/blob/master/src/components/app/SingleStrategy/index.tsx#L78) and thought I could address that since it seemed straightforward enough as I'm new to the codebase and looking for places to contribute.

I've took the liberty of adding [factory.ts](https://www.npmjs.com/package/factory.ts) so that we could potentially have a little bit more testing in the codebase, happy to remove if need be.

### CODE REVIEW

**Comment by storming0x** [comment]
@karelianpie can you fix the conflicts pulling latest?

**Review by storming0x — COMMENTED** [review]
Great job adding tests and refactoring

**Comment by karelianpie** [comment]
> @karelianpie can you fix the conflicts pulling latest?

Done

**Review by storming0x — APPROVED** [review]
Great work!, LGTM!

**Pull request merged**
