### PR TITLE
Refactor vault service

### LINKED ISSUE #216: Optimize initial page load for home page and healthcheck report
* The current way we batch fetch data and perform sorting can block the UI rendering thread for a while before you can interact with the page again. We should be able to optimize this with better lazy loading (eg. only load next batch after scrolling to the bottom of the list)

### PR DESCRIPTION
**Pull request by edwinzhng**
- Cleans up a bunch of TODOs in the code, and makes it easier to tackle #216
- Standardizes how we fetch vaults, so that mainnet now uses the SDK
    - We now have 356 strategies vs 249 from before, since we fetch mainnet strategies from the subgraph now
- Move fetch logic from home pages into a hook
- Refactored VaultService into an abstract class that the networks can inherit from, and reduce duplicate code significantly

### CODE REVIEW

**Comment by 0xkofee** [comment]
hey @edwinzhng is this still being worked on?

**Comment by edwinzhng** [comment]
> hey @edwinzhng is this still being worked on?

Should be good now was just in the middle of rebasing when you commented 😅

**Comment by 0xkofee** [comment]
hey @edwinzhng  who do we need to talk to in order to get this looked at? it's quite a lot of changes. you're gonna have massive merge conflicts if you let this linger. I posted on telegram so lets see....

**Review by magikadev — APPROVED** [review]
LGTM!

**Review by storming0x — APPROVED** [review]
@edwinzhng great work, i reviewed most of the refactoring, LGTM!

We can keep an eye out for regressions or issues when they get reported, given the size of this PR i expect to have some minor issues but i think the code benefits outweigh the small regression problems.

**Pull request merged**
