### PR TITLE
feat: Upgrade MUI

### LINKED ISSUE #219: Upgrade Material UI Version
material-ui/core is deprecated, we need to upgrade to use mui

Reference
https://www.npmjs.com/package/@material-ui/core

### PR DESCRIPTION
**Pull request by phillip055**
fixes #219 
Known Issues from this upgrade which i suggest is fixed on separate PRs:

- ContainerLg Margins, squishes the screen
- Some icons are not supporting dark mode
- Breadcrumbs are not on secondary color

Steps that was followed:
https://mui.com/guides/migration-v4/

This will allow us to move faster when refactoring or implementing the new layouts.

### CODE REVIEW

**Review by edwinzhng — COMMENTED** [review]
nice, good change. I feel like we should just fix those 3 issues you mentioned in the same PR if it's going to degrade the UX (especially on dark mode) but i'll let @magic990619 and @storming0x decide

**Comment by magikadev** [comment]
> nice, good change. I feel like we should just fix those 3 issues you mentioned in the same PR if it's going to degrade the UX (especially on dark mode) but i'll let @magic990619 and @storming0x decide

It would be better to fix these 3 issues on one PR. I will open a new issue for this.

**Comment by magikadev** [comment]
Good catch and work. @phillip055 .

image

Please fix the problem.

And since other PRs have been merged, there are some conflicts with your PR. 
Would you please rebase your branch with the latest master and commit?

FYI: Please name the comments on each commit meaningful, so that others can get the idea of what you have done on this commit.

**Comment by phillip055** [comment]
Noted(assumed, it's gonna be squashed merged anyway). Will do better, will fix these on this PR, and request for review again.

**Comment by phillip055** [comment]
Found an issue with SingleVault Screen, having a look

**Pull request merged**
